// Wrappers around items provided by dxgiformat.h
use winapi;

pub enum DXGIFormat {
    Unknown,
    Red32Green32Blue32Alpha32Typeless,
    Red32Green32Blue32Alpha32Float,
    Red32Green32Blue32Alpha32UnsignedInteger,
    Red32Green32Blue32Alpha32SignedInteger,
    Red32Green32Blue32Typeless,
    Red32Green32Blue32Float,
    Red32Green32Blue32UnsignedInteger,
    Red32Green32Blue32SignedInteger,
    Red16Green16Blue16Alpha16Typeless,
    Red16Green16Blue16Alpha16Float,
    Red16Green16Blue16Alpha16UnsignedNormalized,
    Red16Green16Blue16Alpha16UnsignedInteger,
    Red16Green16Blue16Alpha16SignedNormalized,
    Red16Green16Blue16Alpha16SignedInteger,
    Red32Green32Typeless,
    Red32Green32Float,
    Red32Green32UnsignedInteger,
    Red32Green32SignedInteger,
    Red32Green8X24Typeless,
    Depth32FloatStencil8X24UnsignedInteger,
    Red32FloatX8X24Typeless,
    X32TypelessGreen8X24UnsignedInteger,
    Red10Green10Blue10Alpha2Typeless,
    Red10Green10Blue10Alpha2UnsignedNormalized,
    Red10Green10Blue10Alpha2UnsignedInteger,
    Red11Green11Blue10Float,
    Red8Green8Blue8Alpha8Typeless,
    Red8Green8Blue8Alpha8UnsignedNormalized,
    Red8Green8Blue8Alpha8UnsignedNormalizedsRGB,
    Red8Green8Blue8Alpha8UnsignedInteger,
    Red8Green8Blue8Alpha8SignedNormalized,
    Red8Green8Blue8Alpha8SignedInteger,
    Red16Green16Typeless,
    Red16Green16Float,
    Red16Green16UnsignedNormalized,
    Red16Green16UnsignedInteger,
    Red16Green16SignedNormalized,
    Red16Green16SignedInteger,
    Red32Typeless,
    Depth32Float,
    Red32Float,
    Red32UnsignedInteger,
    Red32SignedInteger,
    Red24Green8Typeless,
    Depth24UnsignedNormalizedStencil8UnsignedInteger,
    Red24UnsignedNormalizedX8Typeless,
    X24TypelessGreen8UnsignedInteger,
    Red8Green8Typeless,
    Red8Green8UnsignedNormalized,
    Red8Green8UnsignedInteger,
    Red8Green8SignedNormalized,
    Red8Green8SignedInteger,
    Red16Typeless,
    Red16Float,
    Depth16UnsignedNormalized,
    Red16UnsignedNormalized,
    Red16UnsignedInteger,
    Red16SignedNormalized,
    Red16SignedInteger,
    Red8Typeless,
    Red8UnsignedNormalized,
    Red8UnsignedInteger,
    Red8SignedNormalized,
    Red8SignedInteger,
    Alpha8UnsignedNormalized,
    Red1UnsignedNormalized,
    Red9Green9Blue9Exponent5SharedExponent,
    Red8Green8Blue8Green8UnsignedNormalized,
    Green8Red8Green8Blue8UnsignedNormalized,
    BC1Typeless,
    BC1UnsignedNormalized,
    BC1UnsignedNormalizedsRGB,
    BC2Typeless,
    BC2UnsignedNormalized,
    BC2UnsignedNormalizedsRGB,
    BC3Typeless,
    BC3UnsignedNormalized,
    BC3UnsignedNormalizedsRGB,
    BC4Typeless,
    BC4UnsignedNormalized,
    BC4SignedNormalized,
    BC5Typeless,
    BC5UnsignedNormalized,
    BC5SignedNormalized,
    Blue5Green6Red5UnsignedNormalized,
    Blue5Green5Red5Alpha1UnsignedNormalized,
    Blue8Green8Red8Alpha8UnsignedNormalized,
    Blue8Green8Red8X8UnsignedNormalized,
    Red10Green10Blue10XRBiasAlpha2UnsignedNormalized,
    Blue8Green8Red8Alpha8Typeless,
    Blue8Green8Red8Alpha8UnsignedNormalizedsRGB,
    Blue8Green8Red8X8Typeless,
    Blue8Green8Red8X8UnsignedNormalizedsRGB,
    BC6HTypeless,
    BC6HUnsignedFloat16,
    BC6HSignedFloat16,
    BC7Typeless,
    BC7UnsignedNormalized,
    BC7UnsignedNormalizedsRGB,
    AYUV,
    Y410,
    Y416,
    NV12,
    P010,
    P016,
    Opaque420,
    YUY2,
    Y210,
    Y216,
    NV11,
    AI44,
    IA44,
    Palletized8,
    Alpha8Palletized8,
    Blue4Green4Red4Alpha4UnsignedNormalized,
    P208,
    V208,
    V408,
}

impl From<DXGIFormat> for winapi::DXGI_FORMAT {
    fn from(source: DXGIFormat) -> winapi::DXGI_FORMAT {
        match source {
            DXGIFormat::Unknown => winapi::DXGI_FORMAT_UNKNOWN,
            DXGIFormat::Red32Green32Blue32Alpha32Typeless => winapi::DXGI_FORMAT_R32G32B32A32_TYPELESS,
            DXGIFormat::Red32Green32Blue32Alpha32Float => winapi::DXGI_FORMAT_R32G32B32A32_FLOAT,
            DXGIFormat::Red32Green32Blue32Alpha32UnsignedInteger => winapi::DXGI_FORMAT_R32G32B32A32_UINT,
            DXGIFormat::Red32Green32Blue32Alpha32SignedInteger => winapi::DXGI_FORMAT_R32G32B32A32_SINT,
            DXGIFormat::Red32Green32Blue32Typeless => winapi::DXGI_FORMAT_R32G32B32_TYPELESS,
            DXGIFormat::Red32Green32Blue32Float => winapi::DXGI_FORMAT_R32G32B32_FLOAT,
            DXGIFormat::Red32Green32Blue32UnsignedInteger => winapi::DXGI_FORMAT_R32G32B32_UINT,
            DXGIFormat::Red32Green32Blue32SignedInteger => winapi::DXGI_FORMAT_R32G32B32_SINT,
            DXGIFormat::Red16Green16Blue16Alpha16Typeless => winapi::DXGI_FORMAT_R16G16B16A16_TYPELESS,
            DXGIFormat::Red16Green16Blue16Alpha16Float => winapi::DXGI_FORMAT_R16G16B16A16_FLOAT,
            DXGIFormat::Red16Green16Blue16Alpha16UnsignedNormalized => winapi::DXGI_FORMAT_R16G16B16A16_UNORM,
            DXGIFormat::Red16Green16Blue16Alpha16UnsignedInteger => winapi::DXGI_FORMAT_R16G16B16A16_UINT,
            DXGIFormat::Red16Green16Blue16Alpha16SignedNormalized => winapi::DXGI_FORMAT_R16G16B16A16_SNORM,
            DXGIFormat::Red16Green16Blue16Alpha16SignedInteger => winapi::DXGI_FORMAT_R16G16B16A16_SINT,
            DXGIFormat::Red32Green32Typeless => winapi::DXGI_FORMAT_R32G32_TYPELESS,
            DXGIFormat::Red32Green32Float => winapi::DXGI_FORMAT_R32G32_FLOAT,
            DXGIFormat::Red32Green32UnsignedInteger => winapi::DXGI_FORMAT_R32G32_UINT,
            DXGIFormat::Red32Green32SignedInteger => winapi::DXGI_FORMAT_R32G32_SINT,
            DXGIFormat::Red32Green8X24Typeless => winapi::DXGI_FORMAT_R32G8X24_TYPELESS,
            DXGIFormat::Depth32FloatStencil8X24UnsignedInteger => winapi::DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
            DXGIFormat::Red32FloatX8X24Typeless => winapi::DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
            DXGIFormat::X32TypelessGreen8X24UnsignedInteger => winapi::DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
            DXGIFormat::Red10Green10Blue10Alpha2Typeless => winapi::DXGI_FORMAT_R10G10B10A2_TYPELESS,
            DXGIFormat::Red10Green10Blue10Alpha2UnsignedNormalized => winapi::DXGI_FORMAT_R10G10B10A2_UNORM,
            DXGIFormat::Red10Green10Blue10Alpha2UnsignedInteger => winapi::DXGI_FORMAT_R10G10B10A2_UINT,
            DXGIFormat::Red11Green11Blue10Float => winapi::DXGI_FORMAT_R11G11B10_FLOAT,
            DXGIFormat::Red8Green8Blue8Alpha8Typeless => winapi::DXGI_FORMAT_R8G8B8A8_TYPELESS,
            DXGIFormat::Red8Green8Blue8Alpha8UnsignedNormalized => winapi::DXGI_FORMAT_R8G8B8A8_UNORM,
            DXGIFormat::Red8Green8Blue8Alpha8UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
            DXGIFormat::Red8Green8Blue8Alpha8UnsignedInteger => winapi::DXGI_FORMAT_R8G8B8A8_UINT,
            DXGIFormat::Red8Green8Blue8Alpha8SignedNormalized => winapi::DXGI_FORMAT_R8G8B8A8_SNORM,
            DXGIFormat::Red8Green8Blue8Alpha8SignedInteger => winapi::DXGI_FORMAT_R8G8B8A8_SINT,
            DXGIFormat::Red16Green16Typeless => winapi::DXGI_FORMAT_R16G16_TYPELESS,
            DXGIFormat::Red16Green16Float => winapi::DXGI_FORMAT_R16G16_FLOAT,
            DXGIFormat::Red16Green16UnsignedNormalized => winapi::DXGI_FORMAT_R16G16_UNORM,
            DXGIFormat::Red16Green16UnsignedInteger => winapi::DXGI_FORMAT_R16G16_UINT,
            DXGIFormat::Red16Green16SignedNormalized => winapi::DXGI_FORMAT_R16G16_SNORM,
            DXGIFormat::Red16Green16SignedInteger => winapi::DXGI_FORMAT_R16G16_SINT,
            DXGIFormat::Red32Typeless => winapi::DXGI_FORMAT_R32_TYPELESS,
            DXGIFormat::Depth32Float => winapi::DXGI_FORMAT_D32_FLOAT,
            DXGIFormat::Red32Float => winapi::DXGI_FORMAT_R32_FLOAT,
            DXGIFormat::Red32UnsignedInteger => winapi::DXGI_FORMAT_R32_UINT,
            DXGIFormat::Red32SignedInteger => winapi::DXGI_FORMAT_R32_SINT,
            DXGIFormat::Red24Green8Typeless => winapi::DXGI_FORMAT_R24G8_TYPELESS,
            DXGIFormat::Depth24UnsignedNormalizedStencil8UnsignedInteger => winapi::DXGI_FORMAT_D24_UNORM_S8_UINT,
            DXGIFormat::Red24UnsignedNormalizedX8Typeless => winapi::DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
            DXGIFormat::X24TypelessGreen8UnsignedInteger => winapi::DXGI_FORMAT_X24_TYPELESS_G8_UINT,
            DXGIFormat::Red8Green8Typeless => winapi::DXGI_FORMAT_R8G8_TYPELESS,
            DXGIFormat::Red8Green8UnsignedNormalized => winapi::DXGI_FORMAT_R8G8_UNORM,
            DXGIFormat::Red8Green8UnsignedInteger => winapi::DXGI_FORMAT_R8G8_UINT,
            DXGIFormat::Red8Green8SignedNormalized => winapi::DXGI_FORMAT_R8G8_SNORM,
            DXGIFormat::Red8Green8SignedInteger => winapi::DXGI_FORMAT_R8G8_SINT,
            DXGIFormat::Red16Typeless => winapi::DXGI_FORMAT_R16_TYPELESS,
            DXGIFormat::Red16Float => winapi::DXGI_FORMAT_R16_FLOAT,
            DXGIFormat::Depth16UnsignedNormalized => winapi::DXGI_FORMAT_D16_UNORM,
            DXGIFormat::Red16UnsignedNormalized => winapi::DXGI_FORMAT_R16_UNORM,
            DXGIFormat::Red16UnsignedInteger => winapi::DXGI_FORMAT_R16_UINT,
            DXGIFormat::Red16SignedNormalized => winapi::DXGI_FORMAT_R16_SNORM,
            DXGIFormat::Red16SignedInteger => winapi::DXGI_FORMAT_R16_SINT,
            DXGIFormat::Red8Typeless => winapi::DXGI_FORMAT_R8_TYPELESS,
            DXGIFormat::Red8UnsignedNormalized => winapi::DXGI_FORMAT_R8_UINT,
            DXGIFormat::Red8UnsignedInteger => winapi::DXGI_FORMAT_R8_UNORM,
            DXGIFormat::Red8SignedNormalized => winapi::DXGI_FORMAT_R8_SNORM,
            DXGIFormat::Red8SignedInteger => winapi::DXGI_FORMAT_R8_SINT,
            DXGIFormat::Alpha8UnsignedNormalized => winapi::DXGI_FORMAT_A8_UNORM,
            DXGIFormat::Red1UnsignedNormalized => winapi::DXGI_FORMAT_R1_UNORM,
            DXGIFormat::Red9Green9Blue9Exponent5SharedExponent => winapi::DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
            DXGIFormat::Red8Green8Blue8Green8UnsignedNormalized => winapi::DXGI_FORMAT_R8G8_B8G8_UNORM,
            DXGIFormat::Green8Red8Green8Blue8UnsignedNormalized => winapi::DXGI_FORMAT_G8R8_G8B8_UNORM,
            DXGIFormat::BC1Typeless => winapi::DXGI_FORMAT_BC1_TYPELESS,
            DXGIFormat::BC1UnsignedNormalized => winapi::DXGI_FORMAT_BC1_UNORM,
            DXGIFormat::BC1UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_BC1_UNORM_SRGB,
            DXGIFormat::BC2Typeless => winapi::DXGI_FORMAT_BC2_TYPELESS,
            DXGIFormat::BC2UnsignedNormalized => winapi::DXGI_FORMAT_BC2_UNORM,
            DXGIFormat::BC2UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_BC2_UNORM_SRGB,
            DXGIFormat::BC3Typeless => winapi::DXGI_FORMAT_BC3_TYPELESS,
            DXGIFormat::BC3UnsignedNormalized => winapi::DXGI_FORMAT_BC3_UNORM,
            DXGIFormat::BC3UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_BC3_UNORM_SRGB,
            DXGIFormat::BC4Typeless => winapi::DXGI_FORMAT_BC4_TYPELESS,
            DXGIFormat::BC4UnsignedNormalized => winapi::DXGI_FORMAT_BC4_UNORM,
            DXGIFormat::BC4SignedNormalized => winapi::DXGI_FORMAT_BC4_SNORM,
            DXGIFormat::BC5Typeless => winapi::DXGI_FORMAT_BC5_TYPELESS,
            DXGIFormat::BC5UnsignedNormalized => winapi::DXGI_FORMAT_BC5_UNORM,
            DXGIFormat::BC5SignedNormalized => winapi::DXGI_FORMAT_BC5_SNORM,
            DXGIFormat::Blue5Green6Red5UnsignedNormalized => winapi::DXGI_FORMAT_B5G6R5_UNORM,
            DXGIFormat::Blue5Green5Red5Alpha1UnsignedNormalized => winapi::DXGI_FORMAT_B5G5R5A1_UNORM,
            DXGIFormat::Blue8Green8Red8Alpha8UnsignedNormalized => winapi::DXGI_FORMAT_B8G8R8A8_UNORM,
            DXGIFormat::Blue8Green8Red8X8UnsignedNormalized => winapi::DXGI_FORMAT_B8G8R8X8_UNORM,
            DXGIFormat::Red10Green10Blue10XRBiasAlpha2UnsignedNormalized => winapi::DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
            DXGIFormat::Blue8Green8Red8Alpha8Typeless => winapi::DXGI_FORMAT_B8G8R8A8_TYPELESS,
            DXGIFormat::Blue8Green8Red8Alpha8UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
            DXGIFormat::Blue8Green8Red8X8Typeless => winapi::DXGI_FORMAT_B8G8R8X8_TYPELESS,
            DXGIFormat::Blue8Green8Red8X8UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
            DXGIFormat::BC6HTypeless => winapi::DXGI_FORMAT_BC6H_TYPELESS,
            DXGIFormat::BC6HUnsignedFloat16 => winapi::DXGI_FORMAT_BC6H_UF16,
            DXGIFormat::BC6HSignedFloat16 => winapi::DXGI_FORMAT_BC6H_SF16,
            DXGIFormat::BC7Typeless => winapi::DXGI_FORMAT_BC7_TYPELESS,
            DXGIFormat::BC7UnsignedNormalized => winapi::DXGI_FORMAT_BC7_UNORM,
            DXGIFormat::BC7UnsignedNormalizedsRGB => winapi::DXGI_FORMAT_BC7_UNORM_SRGB,
            DXGIFormat::AYUV => winapi::DXGI_FORMAT_AYUV,
            DXGIFormat::Y410 => winapi::DXGI_FORMAT_Y410,
            DXGIFormat::Y416 => winapi::DXGI_FORMAT_Y416,
            DXGIFormat::NV12 => winapi::DXGI_FORMAT_NV12,
            DXGIFormat::P010 => winapi::DXGI_FORMAT_P010,
            DXGIFormat::P016 => winapi::DXGI_FORMAT_P016,
            DXGIFormat::Opaque420 => winapi::DXGI_FORMAT_420_OPAQUE,
            DXGIFormat::YUY2 => winapi::DXGI_FORMAT_YUY2,
            DXGIFormat::Y210 => winapi::DXGI_FORMAT_Y210,
            DXGIFormat::Y216 => winapi::DXGI_FORMAT_Y216,
            DXGIFormat::NV11 => winapi::DXGI_FORMAT_NV11,
            DXGIFormat::AI44 => winapi::DXGI_FORMAT_AI44,
            DXGIFormat::IA44 => winapi::DXGI_FORMAT_IA44,
            DXGIFormat::Palletized8 => winapi::DXGI_FORMAT_P8,
            DXGIFormat::Alpha8Palletized8 => winapi::DXGI_FORMAT_A8P8,
            DXGIFormat::Blue4Green4Red4Alpha4UnsignedNormalized => winapi::DXGI_FORMAT_B4G4R4A4_UNORM,
            DXGIFormat::P208 => winapi::DXGI_FORMAT_P208,
            DXGIFormat::V208 => winapi::DXGI_FORMAT_V208,
            DXGIFormat::V408 => winapi::DXGI_FORMAT_V408,
        }
    }
}
